name: forwardious
description: "A simple chrome extension to forward youtube urls to an invidious instance"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  chrome_extension:
  flutter_bloc: ^8.1.4
  http:
  shared_preferences: ^2.2.2
  slang: ^3.30.1
  slang_flutter: ^3.30.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
